#!/bin/bash
if [ ! -e "/etc/dam-vmssystems/path.txt" ]; then
    installationDirectory="/home/DAM VMS"
else
    installationDirectory=$(cat /etc/dam-vmssystems/cctv.txt)
fi
cd "$installationDirectory" || exit
currentBuild=$(git show --oneline -s)
# gitOrigin=$(git remote show origin)
splitBuildString=($currentBuild)
currentCommitNumber=${splitBuildString[0]}
repo="Pro"
if [[ $@ == *'help'* ]] || [ ! "$1" ]; then
    echo "========================================================="
    echo "==!! DAM VMS : The Open Source CCTV and NVR Solution !!=="
    echo "========================================================="
    if [ ! "$1" ]; then
        echo "You are missing function parameters."
        echo "Example : dam-vms [command] .."
        echo "Example : dam-vms flush restart logs"
    else
        echo "Hello there! if you need support come on over"
        echo "to the DAM VMS Community Chat! :)"
        echo "https://discordapp.com/invite/mdhmvuH/"
    fi
    echo "========================================================="
    echo "Your available options for COMMAND are as follows"
    echo "========================================================="
    echo "| start :"
    echo "|--> Start camera.js and cron.js under PM2 (Process Manager)"
    echo "-"
    echo "| restart :"
    echo "|--> Restart all processes running under the PM2 daemon."
    echo "-"
    echo "| stop, exit :"
    echo "|--> Stop all processes running under the PM2 daemon."
    echo "-"
    echo "| version :"
    echo "|--> get version of your current build by git."
    echo "-"
    echo "| logs :"
    echo "|--> Get PM2 log stream with last 100 lines."
    echo "-"
    echo "| update :"
    echo "|--> Update via Git."
    echo "-"
    echo "| getMaster :"
    echo "|--> Switch to the Master Branch."
    echo "-"
    echo "| getDev :"
    echo "|--> Switch to the Development Branch."
    echo "-"
    echo "| clear, flush :"
    echo "|--> Clear all PM2 logs."
    echo "-"
    echo "| bootupEnable :"
    echo "|--> Start DAM VMS on OS reboot."
    echo "-"
    echo "| bootupDisable :"
    echo "|--> Disable starting DAM VMS on OS reboot."
    echo "-"
    echo "| kill :"
    echo "|--> Stop the entire PM2 daemon."
fi
if [[ $@ == *'clear'* ]] || [[ $@ == *'flush'* ]]; then
    pm2 flush
fi
if [[ $@ == *'restart'* ]]; then
    pm2 restart camera
else
    if [[ $@ == *'start'* ]] || [[ $@ == *'now'* ]]; then
        echo "Starting DAM VMS"
        pm2 start camera
    fi
fi
if [[ $@ == *'stop'* ]] || [[ $@ == *'exit'* ]]; then
    proccessAlive=$(pm2 list | grep camera)
    if [ "$proccessAlive" ]; then
        pm2 stop camera
    else
        echo "DAM VMS process is not running."
    fi
fi
if [[ $@ == *'version'* ]]; then
    echo "Build ID : $currentCommitNumber"
    if [[ $repo == "Pro" ]]; then
        echo "Repository : DAM VMS Pro"
    else
        echo "Repository : DAM VMS CE"
    fi
    echo "$currentBuild"
fi
if [[ $@ == *'bootupEnable'* ]] || [[ $@ == *'bootupenable'* ]]; then
    pm2 startup
    pm2 save
fi
if [[ $@ == *'bootupDisable'* ]] || [[ $@ == *'bootupdisable'* ]]; then
    pm2 unstartup
    pm2 save
fi
if [[ $@ == *'getDev'* ]] || [[ $@ == *'getdev'* ]]; then
    git checkout dev
    echo "DAM VMS - Restart DAM VMS to make the changes take affect."
fi
if [[ $@ == *'getMaster'* ]] || [[ $@ == *'getmaster'* ]]; then
    git checkout master
    echo "DAM VMS - Restart DAM VMS to make the changes take affect."
fi
if [[ $@ == *'update'* ]]; then
    echo "============="
    echo "DAM VMS - Are you sure you want to update? This will restart DAM VMS."
    echo "(y)es or (N)o"
    read -r updatedam-vms
    if [ "$updatedam-vms" = "y" ] || [ "$updatedam-vms" = "Y" ]; then
        echo "Beginning Update Process..."
        pm2 stop camera.js
        rm -rf node_modules
        sh UPDATE.sh
        pm2 start camera.js
    else
        echo "Cancelled Update Process."
    fi
fi
if [[ $@ == *'kill'* ]]; then
    pm2 kill
fi
if [[ $@ == *'logs'* ]]; then
    pm2 logs --lines 100
fi
